In [1]:
import random 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import xlwt
import xlrd
import openpyxl

In [2]:
xls = pd.ExcelFile("ziroom_new.xls")
df_ziroom = pd.read_excel(xls, 0)
df_ziroom = df_ziroom[(True^df_ziroom['经度'].isin([0]))]
df_ziroom = df_ziroom[(True^df_ziroom['纬度'].isin([0]))]

xls = pd.ExcelFile("58_new.xls")
df_58 = pd.read_excel(xls, 0)
df_58 = df_58[(True^df_58['经度'].isin([0]))]
df_58 = df_58[(True^df_58['纬度'].isin([0]))]
df_58 = df_58.drop(columns="小区")

xls = pd.ExcelFile("lianjia_new.xls")
df_lianjia = pd.read_excel(xls, 0)
df_lianjia = df_lianjia[(True^df_lianjia['经度'].isin([0]))]
df_lianjia = df_lianjia[(True^df_lianjia['纬度'].isin([0]))]

xls = pd.ExcelFile("anjuke_new.xls")
df_anjuke = pd.read_excel(xls, 0)
df_anjuke = df_anjuke[(True^df_anjuke['经度'].isin([0]))]
df_anjuke = df_anjuke[(True^df_anjuke['纬度'].isin([0]))]
df_anjuke = df_anjuke.drop(columns="小区")

df = df_ziroom.append(df_58)
df = df.append(df_lianjia)
df = df.append(df_anjuke)

print(df[:5])

   Unnamed: 0          经度         纬度  室  厅      面积     价格
0           0  121.499917  31.272381  1  1   79.46   8790
1           1  121.521813  31.206273  2  1     102   9890
2           2  121.472869  31.284688  2  1   88.57   9990
3           3  121.496374  31.208895  2  1     143  13490
4           4  121.279576  31.327221  2  1  125.75   5390


In [3]:
df_y = df["价格"]
df_X = df.drop(columns=["价格"])
df_X = df_X.loc[:, ~df_X.columns.str.contains('^Unnamed')]

X = df_X.to_numpy()
y = df_y.to_numpy()

print(X.shape)
print(y.shape)
print(X[:5])
print(y[:5])

(9893, 5)
(9893,)
[[121.499917 31.272381 1 1 79.46]
 [121.521813 31.206273 2 1 102.0]
 [121.472869 31.284688 2 1 88.57]
 [121.496374 31.208895 2 1 143.0]
 [121.279576 31.327221 2 1 125.75]]
[8790 9890 9990 13490 5390]
