In [1]:
import random 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import xlwt
import xlrd
import openpyxl

In [6]:
xls = pd.ExcelFile("beike_new.xls")
df_beike = pd.read_excel(xls, 0)
df_beike = df_beike[(True^df_beike['经度'].isin([0]))]
df_beike = df_beike[(True^df_beike['纬度'].isin([0]))]

xls = pd.ExcelFile("ziroom_new.xls")
df_ziroom = pd.read_excel(xls, 0)
df_ziroom = df_ziroom[(True^df_ziroom['经度'].isin([0]))]
df_ziroom = df_ziroom[(True^df_ziroom['纬度'].isin([0]))]

xls = pd.ExcelFile("ziroom_new.xls")
df_ziroom = pd.read_excel(xls, 0)
df_ziroom = df_ziroom[(True^df_ziroom['经度'].isin([0]))]
df_ziroom = df_ziroom[(True^df_ziroom['纬度'].isin([0]))]

xls = pd.ExcelFile("58_new.xls")
df_58 = pd.read_excel(xls, 0)
df_58 = df_58[(True^df_58['经度'].isin([0]))]
df_58 = df_58[(True^df_58['纬度'].isin([0]))]
df_58 = df_58.drop(columns="小区")

xls = pd.ExcelFile("lianjia_new.xls")
df_lianjia = pd.read_excel(xls, 0)
df_lianjia = df_lianjia[(True^df_lianjia['经度'].isin([0]))]
df_lianjia = df_lianjia[(True^df_lianjia['纬度'].isin([0]))]

xls = pd.ExcelFile("anjuke_new.xls")
df_anjuke = pd.read_excel(xls, 0)
df_anjuke = df_anjuke[(True^df_anjuke['经度'].isin([0]))]
df_anjuke = df_anjuke[(True^df_anjuke['纬度'].isin([0]))]
df_anjuke = df_anjuke.drop(columns="小区")

df = df_ziroom.append(df_58)
df = df.append(df_lianjia)
df = df.append(df_anjuke)
df = df.append(df_beike)
print(df[:5])

   Unnamed: 0          经度         纬度  室  厅      面积     价格
0           0  121.499917  31.272381  1  1   79.46   8790
1           1  121.521813  31.206273  2  1     102   9890
2           2  121.472869  31.284688  2  1   88.57   9990
3           3  121.496374  31.208895  2  1     143  13490
4           4  121.279576  31.327221  2  1  125.75   5390


In [17]:

df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
Xy = df.to_numpy()
Xy = Xy[~np.isnan(Xy).any(axis=1)]
y = Xy[:,5]
X = Xy[:,[0,1,2,3,4]]

print(X.shape)
print(y.shape)
print(X[:5])
print(y[:5])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

print(X_train.shape)
print(X_test.shape)

[[121.499917 31.272381 1 1 79.46 8790]
 [121.521813 31.206273 2 1 102.0 9890]
 [121.472869 31.284688 2 1 88.57 9990]
 ...
 [121.318524 31.131572 3 2 100.0 4000]
 [121.324679 31.327773 1 0 16.0 1000]
 [121.394778 31.146869 2 2 99.0 6500]]


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures
from sklearn.metrics import mean_squared_error

# Design the pipeline as a sequence of steps each step
# is specified as a tuple ('name',model). We will refer
# to this name later.
pipeline = Pipeline([
    ('mm',   MinMaxScaler()),
    ('ploy', PolynomialFeatures()),
    ('sgd',  SGDRegressor(penalty="l2",max_iter=1000,tol=1e-4,alpha=0,random_state=0)),
])

# Train using the whole pipeline using just 1 call!
pipeline.fit(X_train,y_train)

# Report the MSE error on the test-set by calling
pred = pipeline.predict(X_test)

mse = mean_squared_error(pred, y_test)
print("Pipeline MSE %.2f" % mse)

ValueError: could not convert string to float: '22-24'